FROM elixir:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN mix local.hex --force \
    && mix archive.install --force hex phx_new \
    && apt-get update \
    && curl -sL https://deb.nodesource.com/setup_lts.x | bash \
    && apt-get install -y apt-utils \
    && apt-get install -y nodejs \
    && apt-get install -y build-essential \
    && apt-get install -y inotify-tools \
    && apt-get -yqq install docker.io \
    && mix local.rebar --force\
    && curl https://sh.rustup.rs -sSf > /tmp/rustup-init.sh \
    && chmod +x /tmp/rustup-init.sh \
    && sh /tmp/rustup-init.sh -y \
    && rm -rf /tmp/rustup-init.sh \
    && apt-get update \
    && apt-get install -y python3-pip python3-dev \
    && cd /usr/local/bin \
    && ln -s /usr/bin/python3 python \
    && pip3 --no-cache-dir install --upgrade pip \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.cargo/bin:${PATH}"

ENV APP_HOME /app

RUN mkdir -p $APP_HOME

COPY . /app

WORKDIR $APP_HOME

RUN mix local.hex --force && mix local.rebar --force \
    && mix deps.get && mix deps.compile

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . .

