FROM python:3.7.5


ENV DEBIAN_FRONTEND=noninteractive

ENV RUST_ARCHIVE=rust-1.14.0-x86_64-unknown-linux-gnu.tar.gz
ENV RUST_DOWNLOAD_URL=https://static.rust-lang.org/dist/$RUST_ARCHIVE


RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev wget

WORKDIR /apps

RUN curl -fsOSL $RUST_DOWNLOAD_URL \
    && curl -s $RUST_DOWNLOAD_URL.sha256 | sha256sum -c - \
    && tar -C /apps -xzf $RUST_ARCHIVE --strip-components=1 \
    && rm $RUST_ARCHIVE \
    && ./install.sh

COPY requirements.txt ./
RUN ls
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY server.py ./server.py

RUN ls

RUN python server.py